// Exportar todos os schemas de uma vez
export * from './productSchemas'
export * from './categorySchemas'
export * from './contatosSchemas'
export * from './informacoesBasicasSchemas'
export * from './documentosSchemas'
export * from './enderecoSchemas'
export * from './entregaSchemas'
export * from './pagamentoSchemas'
export * from './horarioSchemas'
export * from './createStoreSchemas'
export * from './customerProfileSchemas'
